# Generated by Django 5.0.6 on 2024-06-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jjapp", "0002_alter_result_marks_obtained"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="advanced_payment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
